logger:
  level: debug
  mode: pretty

app:
    port: :8080
    hosts:
      - https://jsonplaceholder.typicode.com/todos/1
      - https://jsonplaceholder.typicode.com/todos/2
      - https://jsonplaceholder.typicode.com/todos/3
      - https://jsonplaceholder.typicode.com/todos/4